//go:build !windows

// Package macapp installs and removes the native macOS "Transom.app"
// window host. The app bundle itself (a gzipped tar of Transom.app,
// built from macapp/) is generated by `bash macapp/build.sh` into
// bundle/Transom.app.tar.gz and embedded below; that file is
// gitignored, and a placeholder .gitkeep is committed in its place so
// go:embed always has a match and builds without it still compile.
package macapp

import "embed"

// all: is required because bundle's only committed file (.gitkeep)
// starts with a dot, and go:embed excludes dotfiles unless told
// otherwise; without it a fresh checkout (before macapp/build.sh has
// ever run) would embed zero files and fail to build.
//
//go:embed all:bundle
var bundleFS embed.FS

// tarballPath is bundleFS's path to the embedded app bundle.
const tarballPath = "bundle/Transom.app.tar.gz"

// Available reports whether this build has the Mac app bundle
// embedded (i.e. macapp/build.sh ran before `go build`).
func Available() bool {
	f, err := bundleFS.Open(tarballPath)
	if err != nil {
		return false
	}
	f.Close()
	return true
}
